#
spring:
  # 环境配置：simple|advance|dev|prod
  profiles:
    active: simple

logging:
  config: classpath:logback-dev.xml

# actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
