spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/light_security_simple?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

light:
  security:
    auth-type: simple